language: cpp
sudo: false
dist: trusty

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
    - clang++-6.0

compiler:
  - clang

script:
  - $CXX --version
