language: cpp
sudo: true
dist: trusty

linux_env_conf: &lconf
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl -sSL http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install g++-7 -yq
  - sudo apt-get install clang++-6 -yq
  - export gxx7=g++-7
  - export clangxx6=clang++-6.0

before_install: *lconf

script:
  - $gxx7 --version
  - $clangxx6 --version
