language: cpp
sudo: true
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-7 -y

script:
  - g++-7 --version
  - g++-7 -o main main.cpp -std=c++17
  - ./main
