language: cpp
sudo: true
dist: trusty

matrix:
  include:
    - env: compiler=g++-7
    - env: compiler=clang++-6.0

linux_env_conf: &lconf
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - curl -sSL http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - if [[ "$compiler" == "g++-7" ]]; then sudo apt-get install g++-7 -yq; fi
  - if [[ "$compiler" == "clang++-6.0" ]]; then sudo apt-get install clang++-6 -yq; fi

before_install: *lconf

script:
  - $compiler --version
